apiVersion: v1
kind: Service
metadata:
  name: openttd-game-tcp
  labels:
    app: openttd
spec:
  type: LoadBalancer
  loadBalancerIP: 1.2.3.4
  ports:
  - name: game-tcp
    protocol: TCP
    port: 3979
    targetPort: 3979
  selector:
    app: openttd
