apiVersion: v1
kind: Service
metadata:
  name: openttd-game
  labels:
    app: openttd
spec:
  clusterIP: None
  selector:
    app: openttd
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openttd-game
spec:
  selector:
    matchLabels:
      app: openttd
  serviceName: openttd-game
  template:
    metadata:
      labels:
        app: openttd
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: openttd
        image: mattias/openttd:latest
        ports:
        - containerPort: 3979
          protocol: TCP
          name: game-tcp
        - containerPort: 3979
          protocol: UDP
          name: game-udp
        - containerPort: 3978
          protocol: UDP
          name: advertise-udp
        volumeMounts:
        - name: game-save
          mountPath: /root/.openttd/save
        - name: game-config
          mountPath: /root/.openttd/openttd.cfg
          subPath: openttd.cfg
          readOnly: true
      volumes:
      - name: game-config
        configMap:
          name: openttd-config
  volumeClaimTemplates:
  - metadata:
      name: game-save
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi
