apiVersion: v1
kind: Service
metadata:
  name: openttd-game-1-udp
  labels:
    app: openttd
    game: "1"
spec:
  type: LoadBalancer
  loadBalancerIP: 1.2.3.4
  ports:
  - name: advertise-udp
    protocol: UDP
    port: 3978
    targetPort: 3978
  - name: game-udp
    protocol: UDP
    port: 3979
    targetPort: 3979
  selector:
    app: openttd
    game: "1"
